<a href="https://colab.research.google.com/github/tomonari-masada/course2022-intro2ml/blob/main/04_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# モジュール、パッケージ、ライブラリ
https://docs.python.org/3/tutorial/modules.html
* "A module is a file containing Python definitions and statements."
* "Packages are a way of structuring Python’s module namespace by using “dotted module names”."

https://realpython.com/lessons/scripts-modules-packages-and-libraries/
* "A module is a Python file that’s intended to be imported into scripts or other modules."
* "A package is a collection of related modules that work together to provide certain functionality."
* "A library is an umbrella term that loosely means “a bundle of code.” These can have tens or even hundreds of individual modules that can provide a wide range of functionality."

## mathモジュール

In [ ]:
import math

a = 2.0
b = math.sqrt(a)
print(a, b)
b = math.exp(a)
print(a, b)

2.0 1.4142135623730951
2.0 7.38905609893065


## reモジュール
* 正規表現

In [ ]:
import re

s = 'one two one two'
m = re.finditer('one', s)
for match in m:
  print(match.start())

0
8


# NumPyライブラリ

* ベクトルや行列を扱える（他にも様々な機能がある）
 * ベクトルどうしの内積
 * 行列とベクトルの積
 * 行列と行列の積
 * 逆行列
 
* ndarrayという独自のデータ構造を使う
 * ちゃんとコードを書けば高速（ちゃんと書かないと遅い・・・）


## ndarray（NumPyの配列）の作り方

### Pythonのリストから作る

* asは別名をつけるときに使う

In [ ]:
import numpy as np

* NumPyの配列の作成

In [ ]:
a = np.array([-2.0, 1.0, 3.0])
print(a)

[-2.  1.  3.]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([[1,2,3], [4,5,6]])
print(b) # 2行3列の行列(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.T) #ndarrayの属性の例（転置属性）
print(b.T)

[-2.  1.  3.]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a = np.array([1, 2, 3])
print(a * 3)
print(a + 2)

[3 6 9]
[3 4 5]


In [ ]:
b = np.array([2, 2, 0])
print(a + b)

[3 4 3]


In [ ]:
print(a / b)

[0.5 1.  inf]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print(a * b)

[2 4 0]


In [ ]:
print(np.dot(a, b)) #内積

6


### ndarrayの属性

In [ ]:
a = np.array([-2.0, 1.0, 3.0])
b = np.array([[1,2,3], [4,5,6]])

print(type(a)) #ndarray自体のデータ型
print(a.data) #メモリ上での位置
print(a.dtype) #要素のデータ型
print(a.size, b.size)
print(a.itemsize, b.itemsize) #要素のサイズ
print(a.ndim, b.ndim) #次元数
print(a.shape, b.shape) #形状

<class 'numpy.ndarray'>
float64
3 6
8 8
1 2
(3,) (2, 3)


### ndarrayの作り方のいろいろ

In [ ]:
for n in range(0, 10, 2):
  print(n)

0
2
4
6
8


In [ ]:
a = np.arange(10)
print(a)
b = np.arange(0, 10, 2)
print(b)
x = np.linspace(0, 10, 15) #0以上10以下を14等分
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [ ]:
for _ in range(10):
  print(np.random.randn())

-0.34376005633897816
-0.017299892861601926
-0.11382504218884956
-0.5044382022415015
0.11929983996889928
-2.4959208386345693
0.09837409939996683
0.8845397058076216
-0.12653663191425707
-2.779524846046721


In [ ]:
print(np.random.randn()) #正規乱数
a = np.random.randn(2, 3)
print(a)
b = np.random.randn(3, 4)
print(b)
print(np.dot(a, b))
print(np.dot(b, a)) #エラー（なぜ？）

-0.7996495593034367
[[-0.11459726  1.07774647 -0.3382304 ]
 [-0.34992227  1.73485184  1.30738399]]
[[-0.79682068  1.54253754  0.69420646  0.96271436]
 [-1.8507022   0.26299777  1.65191561  1.19312087]
 [ 1.03972771  0.28221514  1.14639395  0.95160281]]
[[-2.25494182  0.0112206   1.31304678  0.85369637]
 [-1.57254545  0.28545748  4.12168764  2.97712302]]


ValueError: ignored

In [ ]:
a = np.zeros([3,3]) #()か[]で囲む必要あり
print(a)
b = np.ones([3,3])
print(b)
print(np.dot(b, b)) #なぜこうなる？

c = np.full((2,5), 10)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[10 10 10 10 10]
 [10 10 10 10 10]]


## 配列の要素を指定する

### インデックス

In [ ]:
a = np.arange(1, 20, 3)
print(a)
print(a[0])
print(a[1])
a[3] = 11
print(a)
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c[0,0])
print(c[0,2])
print(c[1,2])
c[1,2] *= 2
print(c)

[ 1  4  7 10 13 16 19]
1
4
[ 1  4  7 11 13 16 19]
[[1 2 3]
 [4 5 6]]
1
3
6
[[ 1  2  3]
 [ 4  5 12]]


In [ ]:
c = np.array([[[1,2,3],[2,3,4]],[[4,5,6],[6,7,8]]])
print(c)
print(c.shape) # テンソル

[[[1 2 3]
  [2 3 4]]

 [[4 5 6]
  [6 7 8]]]
(2, 2, 3)


### 良くないコードの例

* NumPyの配列をあつかうプログラムでは、できるだけ、forループを書かない！

In [ ]:
import time
import numpy as np

x = np.ones(10000000)
y = np.ones(10000000)
s = np.zeros(10000000)
for _ in range(10):
  a = time.time()
  for i in range(10000000):
    s[i] = x[i] + y[i]
  b = time.time()
  print(b - a)

5.086200475692749
4.980530261993408
4.93688440322876
4.977482318878174
5.0062267780303955
4.985112428665161
4.905304193496704
4.914787769317627
4.987136125564575
4.979875087738037


* 上のセルのように書くより、こう書くほうが良い

In [ ]:
import time
import numpy as np

x = np.ones(10000000)
y = np.ones(10000000)
s = np.zeros(10000000)
for _ in range(10):
  a = time.time()
  s = x + y
  b = time.time()
  print(b - a)

0.04288911819458008
0.025920391082763672
0.021986007690429688
0.021043062210083008
0.021635770797729492
0.020960569381713867
0.023302555084228516
0.020800352096557617
0.021679162979125977
0.02192068099975586


### スライシング

In [ ]:
a = np.arange(1, 20, 3)
print(a)
print(a[1:5])
print(a[0:6:2])
print(a[::-1])
print(a[-2::-1])
print(a[-2:1:-1])

[ 1  4  7 10 13 16 19]
[ 4  7 10 13]
[ 1  7 13]
[19 16 13 10  7  4  1]
[16 13 10  7  4  1]
[16 13 10  7]


### fancy index

In [ ]:
np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)
m = a % 3 == 0
print(m)
print(type(m))
print(m.dtype)
b = a[m]
print(b) 

[3 6 5 4 8 9 1 7 9 6]
[ True  True False False False  True False False  True  True]
<class 'numpy.ndarray'>
bool
[3 6 9 9 6]


### where関数

In [ ]:
np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)
m = np.where(a % 3 == 0) #インデックスのtupleを返す
print(m)
print(type(m))
b = a[m]
print(b) 

[3 6 5 4 8 9 1 7 9 6]
(array([0, 1, 5, 8, 9]),)
<class 'tuple'>
[3 6 9 9 6]


In [ ]:
np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)
m = np.where(a % 2 == 0, 'even', 'odd')
print(m)

print(a[m == 'even'])

[3 6 5 4 8 9 1 7 9 6]
['odd' 'even' 'odd' 'even' 'even' 'odd' 'odd' 'odd' 'odd' 'even']
[6 4 8 6]


## 配列のコピー

### 配列のビュー
* コピーではない

In [ ]:
a = np.array([1, 2, 3])
b = a #ビューを作っている

In [ ]:
print(a)

[1 2 3]


In [ ]:
b[1] = 10

In [ ]:
print(a)

[ 1 10  3]


### 復習：リストのコピー

In [ ]:
a = [1, 2, 3]
b = a 
b[1] = 22
print(a)
print(b)

[1, 22, 3]
[1, 22, 3]


In [ ]:
print(a[:])

[1, 22, 3]


In [ ]:
c = a[:] #リストがコピーされる
c[2] = 234
print(a)
print(c)

[1, 22, 3]
[1, 22, 234]


## ndarrayの場合の`a[:]`

In [ ]:
a = np.array([1, 2, 3])
c = a[:] #コピーされるかどうか？
print(id(a) == id(c))
c[1] = 22
print(a) #変化している

False
[ 1 22  3]


### `copy`メソッド

In [ ]:
a = np.array([1, 2, 3])
d = a.copy() #コピーを作る
d[2] = 234
print(d)
print(a) #変化していない

[  1   2 234]
[1 2 3]


In [ ]:
a = {"one":1, "two":2}
b = a
b["one"] =10
print(a)
print(b)

{'one': 10, 'two': 2}
{'one': 10, 'two': 2}


## in-place演算

In [ ]:
a = np.array([1, 2, 3])
c = a #ビューを作る
a = a + 1 #ここで別のオブジェクトになる
print(c)

a = np.array([1, 2, 3])
c = a #ビューを作る
a += 1 #in-place演算
print(c) #変化している

[1 2 3]
[2 3 4]


### in-place演算と演算関数の比較

In [ ]:
import time
import numpy as np

In [ ]:
size = 100000000
x = np.ones(size)
y = np.ones(size)
for _ in range(10):
  a = time.time()
  x = x * 4 + y * 3
  b = time.time()
  print(b - a)
  x = np.ones(size)
  y = np.ones(size)

0.429105281829834
0.4401087760925293
0.42964649200439453
0.4385106563568115
0.4289278984069824
0.43470239639282227
0.4287228584289551
0.43115925788879395
0.4420304298400879
0.43234682083129883


In [ ]:
size = 100000000
x = np.ones(size)
y = np.ones(size)
for _ in range(10):
  a = time.time()
  x *= 4
  y *= 3
  x += y
  b = time.time()
  print(b - a)
  x = np.ones(size)
  y = np.ones(size)

0.30123090744018555
0.3089332580566406
0.31571531295776367
0.3091440200805664
0.3014671802520752
0.30440616607666016
0.2985825538635254
0.3055691719055176
0.3029203414916992
0.3066377639770508


In [ ]:
import time
import numpy as np

size = 100000000
x = np.ones(size)
y = np.ones(size)
for _ in range(10):
  a = time.time()
  np.multiply(x, 4, out=x)
  np.multiply(y, 3, out=y)
  np.add(x, y, out=x)
  b = time.time()
  print(b - a)
  x = np.ones(size)
  y = np.ones(size)

0.34691810607910156
0.3370184898376465
0.33677101135253906
0.3473992347717285
0.3388340473175049
0.34104061126708984
0.3577144145965576
0.3243751525878906
0.32071876525878906
0.3390650749206543


## 配列の形状を変更する

In [ ]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b = np.reshape(a, (4, 3)) #NumPyの関数reshape
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
a[3] *= -1
print(a)
print(b) #変化している


[ 0  1  2 -3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [-3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
c = a.reshape((2,6)) #ndarrayのreshapeメソッド
print(c)

[[ 0  1  2 -3  4  5]
 [ 6  7  8  9 10 11]]
