<a href="https://colab.research.google.com/github/tomonari-masada/course2022-intro2ml/blob/main/05_NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPyライブラリの説明の続き

* NumPyのインポート

In [ ]:
import numpy as np

## ブロードキャスト

* 同じことを3通りの方法で実施
 * 一番最後の方法がベスト

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)
for i in range(4):
  y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4, 1))
print(vv)
y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


* ブロードキャスト

In [ ]:
print(np.array([[1, 2, 3]]) + [1])

[[2 3 4]]


In [ ]:
a = np.array([[1, 2]])
print(a.shape)
b = np.array([3, 4])
print(b.shape)
c = a + b
print(c)
print(c.shape)

(1, 2)
(2,)
[[4 6]]
(1, 2)


In [ ]:
a = np.array([1,2])
print(a.shape)
b = np.array([[3,4],[2,3]])
print(b.shape)
c = a + b
print(c.shape)
print(c)

(2,)
(2, 2)
(2, 2)
[[4 6]
 [3 5]]


In [ ]:
a = np.array([[1],[2],[3]])
print(a.shape)
b = np.array([[4,8],[5,10],[6,12]])
print(b.shape)
c = a + b
print(c.shape)
print(c)

(3, 1)
(3, 2)
(3, 2)
[[ 5  9]
 [ 7 12]
 [ 9 15]]


In [ ]:
a = np.array([1,2])
print(a.shape)
b = np.array([[3],[4]])
print(b.shape)
c = a * b
print(c.shape)
print(c) # 出力がなぜそうなるか説明してみよう

(2,)
(2, 1)
(2, 2)
[[3 6]
 [4 8]]


## 数学的なデータの処理

* 様々な関数

In [ ]:
print(np.power(2, 3))
print(np.power(2.1, 2.8))

8
7.983880450340076


In [ ]:
a = np.arange(1, 11)
print(np.sqrt(a))
print(np.arctan(a))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.78539816 1.10714872 1.24904577 1.32581766 1.37340077 1.40564765
 1.42889927 1.44644133 1.46013911 1.47112767]


In [ ]:
x = np.linspace(-1, 1, 11)
print(np.exp(x))

[0.36787944 0.44932896 0.54881164 0.67032005 0.81873075 1.
 1.22140276 1.4918247  1.8221188  2.22554093 2.71828183]


* 記述統計

In [ ]:
x = np.random.randn(3, 10)
print(x)
x = x * 3 + 5
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))
print(np.median(x), np.var(x), np.std(x))

[[-2.99232819  1.99275919  2.15471952  0.56427705 -1.32689293 -2.40215196
   0.91603338  0.30571316  1.35621584 -0.18404764]
 [-0.74711545 -0.07850339  0.76944506 -0.27258733  0.47172637 -0.52704556
  -0.25213392 -0.22738694  0.22790361  0.75599574]
 [ 0.88480371 -0.94303782 -1.41432597  2.37627287 -0.98757089  1.06261392
   0.23554118  0.73238069  0.38827493  1.16335219]]
5.4002900435811325
[2.14536007 5.97121799 6.50983861 7.6679626  3.15726255 3.1334164
 5.89944064 5.81070691 6.97239438 6.73530028]
[5.11528923 5.03608946 6.04949144]
5.811881506773312 13.103510731677906 3.619877170799847


In [ ]:
x = np.random.randn(2, 100)
print(x)
print(np.cov(x[0], x[1]))
print(np.corrcoef(x[0], x[1]))

[[-6.46246335e-01 -1.81477639e-02 -8.52619351e-01  4.37134514e-01
   5.82421303e-01  9.53634272e-01  2.33021634e-01  1.20496879e+00
  -5.86063486e-01  4.01607949e-01 -3.37365352e-02  1.59037682e+00
   8.57202007e-01  3.67098013e-01  2.12651507e+00  1.98402074e+00
  -5.96912802e-01 -1.25223651e-01 -9.09785197e-01  4.82919597e-01
  -7.60524543e-01  3.51900208e-01 -1.03676400e+00 -1.07382354e+00
  -1.06133230e-01 -1.58670753e+00  7.87848938e-01 -1.02672326e+00
   2.00693962e+00  4.78196762e-01  1.09935468e+00 -9.52790528e-01
  -9.95024131e-01  1.45474641e+00 -2.76144681e-01 -1.42263345e+00
   3.14661176e-02  1.36469748e-01  9.47008023e-02  1.40442046e+00
  -1.20734371e+00  2.95326767e-01 -5.60859665e-01 -1.03648021e-01
   6.92440394e-01 -6.18032619e-02  9.97516279e-02  1.95000150e+00
  -1.13872594e+00  6.49920516e-01  3.43225689e-01 -2.13744682e+00
  -1.16087356e+00 -4.10346464e-01  1.10870821e+00  7.92260722e-01
   7.91727264e-01  7.75011038e-02  1.03278530e+00 -8.64349419e-01
  -2.44568

# 練習
* 以下のセルを実行して、なぜ出力がそのようになるのか、説明してみよう。

## 行列やベクトルの様々な作り方

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
x = np.arange(50)
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
x = np.array([1,2,0,0,4,0])
nz = np.nonzero(x)
print(nz)
print(x[nz])

(array([0, 1, 4]),)
[1 2 4]


In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Z = np.eye(3)
nz = np.nonzero(Z)
print(nz)
print(Z[nz])

(array([0, 1, 2]), array([0, 1, 2]))
[1. 1. 1.]


In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.016620790534935814 0.9840264735564562


In [ ]:
x = np.random.random(30)
m = x.mean()
print(m)

0.42065348462508795


* NaN
 * NaNとはnot a numberで、非数

In [ ]:
print(0.0 / np.ones(5))

[0. 0. 0. 0. 0.]


In [ ]:
print(0.0 / np.zeros(5))

[nan nan nan nan nan]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


* float形の値の比較（要注意！）

In [ ]:
print(0.3 == 3 * 0.1)
print(0.3 == 2 * 0.15)

False
True


* 計算機は実数を完全に厳密には表現できない

In [ ]:
a = np.array([0.3])
b = np.array([3 * 0.1])
print(a - b)
b = np.array([2 * 0.15])
print(a - b)

[-5.55111512e-17]
[0.]


* 市松模様を作る

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


* 総和

In [ ]:
Z = np.arange(10)
np.sum(Z)

45

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)
# []の中身では何をしている？

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.22633676 0.3397336  0.36433354 0.83259202 0.79215111 0.27371398
 0.70825803 0.47136909 0.40861255 0.23997751]
[0.22633676 0.3397336  0.36433354 0.         0.79215111 0.27371398
 0.70825803 0.47136909 0.40861255 0.23997751]


In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

91


* 高度なデータ分析

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10
